# Resumo
- defini X como entrada e Y como alvo, junto com os pesos theta1 e theta2 baseados no slide da aula 1 parte 4;
- calculei o forward pass de uma rede neural simples:

    z1 = X @ theta1.T

    a1 = sigmoid(z1)

    z2 = a1 @ theta2.T

    a2 = sigmoid(z2)

- usei a2 como saída final e comparei com Y usando o erro quadrático médio mean((a2 - Y)**2);
- então organizei tudo em uma classe MLP com métodos forward e loss para tornar o código mais limpo e reutilizável;
- por fim, testei a classe MLP para obter a previsão e o valor da função de custo.

## Glossário
1. Forward pass: passagem direta dos dados pela rede, do input até a saída, sem ajuste de pesos. Aqui é o cálculo sequencial de z1, a1, z2 e a2.
2. theta1 e theta2: são os pesos da rede neural. theta1 conecta a entrada à primeira camada oculta e theta2 conecta a camada oculta à saída.
3. erro quadrático médio (MSE): métrica que calcula a média dos quadrados da diferença entre a previsão (a2) e o alvo (Y). Mede o quão distante está a previsão do valor correto.

In [2]:
import numpy as np

In [27]:
# Forward Pass

# Dados pegos o slide da aula 1 parte 4.

X = np.array([[0.5, 0.1], 
              [0.2, 0.6]])
# variáveis alvo
Y = np.array([[0.7], 
              [0.8]])

theta1 = np.array([[0.5,   0.2],
                   [0.6,  -0.1],
                   [-0.4, -0.3]])

theta2 = np.array([[0.7, -0.1, 0.2]])

# Forward Pass
## Pré-ativação da camada 1

z1 = X*theta1.T

In [28]:
# z1 -> é a pré-ativação da camada 1

# Transposta de theta1 -> theta1.T
# array([[ 0.5,  0.6, -0.4],
#        [ 0.2, -0.1, -0.3]])
z1 = np.matmul(X, theta1.T)
print(z1.shape)
print(z1)


(2, 3)
[[ 0.27  0.29 -0.23]
 [ 0.22  0.06 -0.26]]


In [29]:
# Computar a função de ativação (no nosso caso, sigmoidal)
def sigmoid(x):
    return 1 / (1 + np.exp(-x)) 

a1 = sigmoid(z1)
print(a1.shape)
print(a1)

(2, 3)
[[0.5670929  0.57199613 0.44275215]
 [0.55477924 0.5149955  0.43536371]]


## Pré-ativação da camada 2

In [30]:
z2 = np.matmul(a1, theta2.T)
print(z2.shape)
print(z2)

(2, 1)
[[0.42831585]
 [0.42391866]]


In [31]:
# Ativação da camada 2
a2 = sigmoid(z2)
print(a2.shape)
print(a2)

(2, 1)
[[0.60547144]
 [0.60442057]]


# Função de Custo!

## (metade) erro médio quadrático

In [32]:
np.mean((a2 - Y)**2)

0.023593481600522263

## movendo toda a lógica para uma classe.

In [ ]:
# vamos sintetizar isso em uma classe.
# MultiLayer Perceptron (MLP)
class MLP():
    def __init__(self):
        self.theta1 = np.array([[0.5, 0.2],
                                [0.6, -0.1],
                                [-0.4, -0.3]])
        self.theta2 = np.array([[0.7, -0.1, 0.2]])
    
    def forward(self, x):
        z1 = np.matmul(x, self.theta1.T)
        a1 = sigmoid(z1)
        z2 = np.matmul(a1, self.theta2.T)
        a2 = sigmoid(z2)
        return a2
    
    def loss(self, y_pred, y_true):
        return np.mean((y_pred - y_true)**2)
    

model = MLP()

In [34]:
model.forward(X)

array([[0.60547144],
       [0.60442057]])

In [37]:
model.loss(model.forward(X), Y)

0.023593481600522263