# Ativação da Camada 1

$a^{1} = 1/(1+e^{-z})$

In [2]:
import numpy as np

In [16]:
class MLP():
    def __init__(self):
        self.theta1 = np.array([[0.5, 0.2],
                                [0.6, -0.1],
                                [-0.4, -0.3]])
        self.theta2 = np.array([[0.7, -0.1, 0.2]])

    def theta1(self):
        return self.theta1

    def theta2(self):
        return self.theta2

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def z1(self, x):
        return np.matmul(x, self.theta1.T) 
    
    def forward(self, x):
        z1 = np.matmul(x, self.theta1.T)
        a1 = self.sigmoid(z1)
        z2 = np.matmul(a1, self.theta2.T)
        a2 = self.sigmoid(z2)
        return a2
    
    def loss(self, y_pred, y_true):
        return np.mean((y_pred - y_true)**2)
    

model = MLP()

In [ ]:
X = np.array([[0.5, 0.1], 
              [0.2, 0.6]])

model.forward(X)

array([[0.60547144],
       [0.60442057]])

## Backward Pass

In [7]:
Y = np.array([[0.7], 
              [0.8]])
a2 = model.forward(X)

delta2 = (a2 - Y) * (a2 * (1 - a2))

delta2

array([[-0.02258058],
       [-0.04676233]])

In [11]:
z1 = model.z1(X)
print("z1:", z1)
a1 = model.sigmoid(z1)
print("a1:", a1)

delta1 = np.matmul(delta2, model.theta2) * (a1 * (1 - a1))

delta1

z1: [[ 0.27  0.29 -0.23]
 [ 0.22  0.06 -0.26]]
a1: [[0.5670929  0.57199613 0.44275215]
 [0.55477924 0.5149955  0.43536371]]


array([[-0.00388045,  0.00055281, -0.00111423],
       [-0.00808518,  0.00116801, -0.00229904]])

In [15]:
grad_theta2 = np.matmul(delta2.T, a1)
print("grad_theta2:", grad_theta2)

grad_theta1 = np.matmul(delta1.T, X)
print("grad_theta1:", grad_theta1)

grad_theta2: [[-0.03874806 -0.03699839 -0.03035622]]
grad_theta1: [[-0.00355726 -0.00523915]
 [ 0.00051001  0.00075609]
 [-0.00101692 -0.00149085]]


## Optmizer

$\theta_{t+1} = \theta_{t} - \eta \cdot \nabla J$

In [23]:
theta1 = model.theta1 - 0.1 * grad_theta1
theta2 = model.theta2 - 0.1 * grad_theta2

theta1



array([[ 0.50035573,  0.20052392],
       [ 0.599949  , -0.10007561],
       [-0.39989831, -0.29985092]])

In [27]:
# calculando novamente a partir dos novos pesos

model.theta1 = theta1
model.theta2 = theta2

In [26]:
model.forward(X)

array([[0.60683258],
       [0.60572302]])

In [29]:
J = model.loss(model.forward(X), Y)
J

0.023211857014709313