In [5]:
%pip install torch

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [6]:
import torch

In [7]:
t1 = torch.ones(2,3)
print("ndim:", t1.ndim)
print("shape:", t1.shape)
print(t1)



ndim: 2
shape: torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
t2 = torch.randn(2,3)
print("ndim:", t2.ndim)
print("shape:", t2.shape)
print(t2)

ndim: 2
shape: torch.Size([2, 3])
tensor([[ 1.3301,  0.1375, -0.8011],
        [ 1.2010, -0.0231,  0.0707]])


In [9]:
torch.matmul(t1, t2.T)

tensor([[0.6665, 1.2486],
        [0.6665, 1.2486]])

In [11]:
t2.T + 10

tensor([[11.3301, 11.2010],
        [10.1375,  9.9769],
        [ 9.1989, 10.0707]])

In [13]:
tensor1 = torch.rand(2,2)
tensor2 = torch.rand(2,3)
print(f'{tensor1}\n{tensor2}')
print(f'{torch.matmul(tensor1, tensor2)}')


tensor([[0.2295, 0.5684],
        [0.8991, 0.3767]])
tensor([[5.8946e-01, 4.1932e-01, 7.4799e-01],
        [1.8495e-01, 2.0373e-04, 7.5464e-01]])
tensor([[0.2404, 0.0964, 0.6006],
        [0.5997, 0.3771, 0.9568]])


In [15]:
## Permitação

x = torch.arange(1., 8.)
print(x, x.shape)

tensor([1., 2., 3., 4., 5., 6., 7.]) torch.Size([7])


In [17]:
x_reshaped = x.reshape(1,7)
print(x_reshaped, x_reshaped.shape)

tensor([[1., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7])
